(function(){"use strict";
var q=new URLSearchParams(location.search), cfg={sat:+q.get("sat")||10,bri:+q.get("bri")||90,revealHold:+q.get("revealHold")||1500,h1:+q.get("hint1")||22000,h2:+q.get("hint2")||45000,wind:+q.get("wind")||30000,creak:+q.get("creak")||60000,badLog:+q.get("badLog")||2600,badRed:+q.get("badRed")||1800,badBlack:+q.get("badBlack")||1200,goodOff:+q.get("goodOff")||900};
var $=function(s){return document.querySelector(s)}, $$=function(s){return Array.from(document.querySelectorAll(s))};
var E={app:$("#app"),intro:$("#intro-screen"),introVideo:$("#intro-video"),introWarning:$("#intro-warning"),introTvHit:$("#intro-tv-hit"),introMessage:$("#intro-message p"),alert:$("#alert-screen"),invite:$("#invite-screen"),inviteHit:$("#invite-hitarea"),inviteCopy:$(".invite-copy"),instructions:$("#instruction-screen"),instructions2:$("#instruction-two-screen"),instructionFamily:$("#instruction-family"),instructionTitle:$("#instruction-title"),instructionTitle2:$("#instruction-title-2"),approachLog:$("#approach-log"),game:$("#game-screen"),ending:$("#ending-tv-screen"),endingHit:$("#ending-tv-hit"),endingImage:$("#ending-tv-image"),endingLog:$("#ending-log p"),endingBroadcast:$("#ending-broadcast"),red:$("#bad-red-filter"),blackout:$("#ending-blackout"),mute:$("#mute-button"),result:$("#result-screen"),crt:$("#crt-hitarea"),instructionPanel:$("#instruction-panel"),instructionPanel2:$("#instruction-panel-2"),instructionBack:$("#instruction-back"),instructionNext:$("#instruction-next"),photoInstructions:$("#photo-instructions"),tvPreview:$("#tv-photo-preview"),tvPhotoHit:$("#tv-photo-hit"),restart:$("#restart-button"),vp:$("#photo-viewport"),stage:$("#photo-stage"),controls:$("#develop-controls"),sat:$("#saturation"),bri:$("#brightness"),satO:$("#sat-output"),briO:$("#bri-output"),fill:$("#exposure-fill"),zoom:$("#zoom-value"),hint:$("#hint"),modal:$("#confirm"),ctitle:$("#confirm-title"),ccopy:$("#confirm-copy"),confirm:$("#confirm-button"),cancel:$("#cancel-button")};
var S={phase:"intro",photoMode:"preview",scale:1.4,tx:0,ty:0,touches:new Map(),gesture:null,ignorePersonClicksUntil:0,controls:false,revealStarted:0,revealed:false,selected:null,started:0,hints:0,muted:true,wind:false,creak:false,goodLog:0,approachLog:null,endingTimers:[]};
var restoringHistory=false;
var introTimer=0,introStep=0;
function viewKey(){if(S.phase==="intro")return "intro";if(S.phase==="alert")return "alert";if(S.phase==="invite")return "invite";if(S.phase==="instructions")return "instructions";if(S.phase==="instructions2")return "instructions2";if(S.phase==="playing"&&S.photoMode==="full")return "photo";if(S.phase==="playing")return "tv";return S.phase}
function pushView(){if(restoringHistory)return;var key=viewKey();if(history.state&&history.state.blessingView===key)return;history.pushState({blessingView:key},"",location.pathname+location.search+"#"+key)}
function historyBack(fallback){if(history.length>1){history.back()}else fallback()}
var A=window.AkashicAnalytics||{track:function(){}};
var SOUND_FILES={wind:"./audio/wind-loop.ogg",creak:"./audio/structural-creak.ogg",distant:"./audio/distant-high-pitch.ogg?v=horror2",recede:"./audio/high-pitch-recede.ogg?v=horror2",bad:"./audio/bad-approach.ogg?v=gdc2026a",message:"./audio/message-click.ogg?v=gdc2026a",relay:"./audio/relay-click.ogg?v=gdc2026a",metal:"./audio/metal-impact.ogg?v=gdc2026a",lowImpact:"./audio/low-impact.ogg?v=gdc2026a",instruction:"./audio/instruction-signal.ogg?v=hallbell1",alarm:"./audio/broadcast-alarm.ogg?v=hallbell1",reveal:"./audio/reveal-stinger.ogg?v=gdc2026a",badCelebration:"./audio/bad-celebration.ogg?v=gdc2026a"};
var audio={ctx:null,master:null,compressor:null,windSource:null,windGain:null,windWanted:false,windGeneration:0,badSource:null,nextCreak:0,buffers:{},loads:{},oneShots:new Set(),generation:0};
function ensureAudio(){if(audio.ctx)return audio.ctx;var C=window.AudioContext||window.webkitAudioContext;if(!C)return null;audio.ctx=new C();audio.master=audio.ctx.createGain();audio.compressor=audio.ctx.createDynamicsCompressor();audio.compressor.threshold.value=-18;audio.compressor.knee.value=18;audio.compressor.ratio.value=5;audio.compressor.attack.value=.006;audio.compressor.release.value=.22;audio.master.gain.value=S.muted?0:1;audio.master.connect(audio.compressor).connect(audio.ctx.destination);return audio.ctx}
function loadSound(name){var c=ensureAudio();if(!c||!SOUND_FILES[name])return Promise.resolve(null);if(audio.buffers[name])return Promise.resolve(audio.buffers[name]);if(audio.loads[name])return audio.loads[name];audio.loads[name]=fetch(SOUND_FILES[name]).then(function(r){if(!r.ok)throw new Error("audio "+r.status);return r.arrayBuffer()}).then(function(data){return c.decodeAudioData(data)}).then(function(buffer){audio.buffers[name]=buffer;delete audio.loads[name];return buffer}).catch(function(){delete audio.loads[name];return null});return audio.loads[name]}
function preloadSounds(){Object.keys(SOUND_FILES).forEach(loadSound)}
function playBuffer(name,options,fallback){var c=ensureAudio();if(!c||S.muted)return;options=options||{};var generation=audio.generation,phase=S.phase;loadSound(name).then(function(buffer){if(S.muted||(!options.ambient&&(generation!==audio.generation||S.phase!==phase))||(options.valid&&!options.valid()))return;if(!buffer){if(fallback)fallback();return}var src=c.createBufferSource(),gain=c.createGain();src.buffer=buffer;src.loop=!!options.loop;src.playbackRate.value=options.rate||1;gain.gain.value=options.gain==null?1:options.gain;src.connect(gain).connect(audio.master);if(!options.ambient){audio.oneShots.add(src);src.onended=function(){audio.oneShots.delete(src)}}src.start();if(options.onstart)options.onstart(src,gain)}).catch(function(){if(fallback&&!S.muted&&generation===audio.generation&&(!options.valid||options.valid()))fallback()})}
function stopOneShots(){audio.generation++;audio.oneShots.forEach(function(src){try{src.stop()}catch(e){}});audio.oneShots.clear()}
function setMuted(value){S.muted=value;var c=ensureAudio();if(c){c.resume().catch(function(){});audio.master.gain.setTargetAtTime(value?0:1,c.currentTime,.025);if(!value)preloadSounds()}if(E.introVideo){E.introVideo.muted=value||S.phase!=="intro";E.introVideo.volume=.72;if(!E.introVideo.muted&&S.phase==="intro")E.introVideo.play().catch(function(){})}E.mute.textContent=value?"MUTED":"SOUND ON";E.mute.classList.toggle("is-on",!value);E.mute.setAttribute("aria-pressed",String(value));E.mute.setAttribute("aria-label",value?"音声をオンにする":"音声をミュートする");if(!value){if(S.wind)startWind();cue("tick")}A.track(value?"audio_muted":"audio_unmuted")}
function tone(from,to,duration,volume,type,delay){var c=ensureAudio();if(!c||S.muted)return;var t=c.currentTime+(delay||0),o=c.createOscillator(),g=c.createGain();o.type=type||"sine";o.frequency.setValueAtTime(from,t);o.frequency.exponentialRampToValueAtTime(Math.max(20,to),t+duration);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(volume,t+Math.min(.035,duration/3));g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(audio.master);audio.oneShots.add(o);o.onended=function(){audio.oneShots.delete(o)};o.start(t);o.stop(t+duration+.03)}
function noiseBurst(duration,volume,lowpass,delay){var c=ensureAudio();if(!c||S.muted)return;var t=c.currentTime+(delay||0),len=Math.ceil(c.sampleRate*duration),b=c.createBuffer(1,len,c.sampleRate),d=b.getChannelData(0);for(var i=0;i<len;i++)d[i]=(Math.random()*2-1)*(1-i/len);var src=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();src.buffer=b;f.type="lowpass";f.frequency.value=lowpass||1800;g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.0001,t+duration);src.connect(f).connect(g).connect(audio.master);audio.oneShots.add(src);src.onended=function(){audio.oneShots.delete(src)};src.start(t)}
function sampleCue(name,gain,rate,fallback){playBuffer(name,{gain:gain,rate:rate||1},fallback)}
function relayFallback(){noiseBurst(.065,.035,2600);tone(125,82,.07,.035,"square")}
function impactFallback(low){noiseBurst(.08,.045,900);tone(low?58:92,low?38:54,low?.42:.28,low?.09:.075,"sawtooth")}
function metalBell(f,delay,gain){tone(f,f,.62,gain,"sine",delay);tone(f*2.71,f*2.71,.46,gain*.36,"sine",delay);tone(f*3.93,f*3.93,.3,gain*.18,"sine",delay);tone(59,59,.7,.009,"sine",delay);noiseBurst(.035,.012,2200,delay)}
function instructionSignal(variant){var notes=variant?[330,392,277]:[330,392,277],starts=[0,.16,.34];notes.forEach(function(f,i){metalBell(f,starts[i],.042)});noiseBurst(.72,.004,850)}
function alertPulse(){var notes=[247,294,233,247,294,233];notes.forEach(function(f,i){metalBell(f,i*.33,.052)});noiseBurst(2.05,.006,900)}
function cue(name){if(S.muted)return;switch(name){case"interrupt":noiseBurst(.085,.055,4300);noiseBurst(.27,.035,520,.08);tone(57,54,.32,.055,"sawtooth",.07);break;case"open":sampleCue("instruction",.72,1,function(){instructionSignal(false)});break;case"receive":sampleCue("instruction",.72,.91,function(){instructionSignal(true)});break;case"photo":sampleCue("lowImpact",.42,1.35,function(){impactFallback(true)});noiseBurst(.16,.012,900);break;case"expand":noiseBurst(.38,.025,520);tone(160,58,.45,.055,"sawtooth");break;case"unlock":sampleCue("metal",.52,.9,function(){impactFallback(false)});sampleCue("relay",.55,.86,relayFallback);break;case"reveal":sampleCue("reveal",.82,1,function(){sampleCue("metal",.5,.68,function(){impactFallback(true)});tone(65,52,.8,.065,"sawtooth")});break;case"select":sampleCue("message",.6,.82,relayFallback);break;case"cancel":sampleCue("relay",.5,.78,relayFallback);break;case"confirm":sampleCue("metal",.6,.82,function(){impactFallback(false)});sampleCue("relay",.45,.72,relayFallback);break;case"message":sampleCue("message",.66,.92+Math.random()*.05,relayFallback);break;case"off":tone(50,32,.28,.06,"sawtooth");sampleCue("relay",.45,.75,relayFallback);break;case"clear":tone(68,39,1.35,.038,"sawtooth");noiseBurst(1.1,.012,480);break;case"red":sampleCue("alarm",.72,1,alertPulse);break;case"blackout":sampleCue("lowImpact",.7,.72,function(){impactFallback(true)});break;case"badresult":sampleCue("badCelebration",.82,1,function(){tone(47,38,1.55,.085,"sawtooth");tone(185,171,1.2,.018,"square",.12);noiseBurst(1.4,.012,420)});break;case"hint":noiseBurst(.055,.018,1400);sampleCue("relay",.25,1.05,relayFallback);break;case"tick":sampleCue("relay",.45,.88,relayFallback);break;case"detent":sampleCue("message",.4,.7,relayFallback);break;case"restart":sampleCue("relay",.55,.7,relayFallback);tone(54,57,.3,.035,"sawtooth",.09);break;case"back":sampleCue("relay",.4,.74,relayFallback);break}}
function proceduralDistantCue(){tone(2100,1700,1.8,.045,"sine")}
function proceduralRecedeCue(){var c=ensureAudio();if(!c||S.muted)return;var o=c.createOscillator(),g=c.createGain(),f=c.createBiquadFilter();o.type="sine";o.frequency.setValueAtTime(1850,c.currentTime);o.frequency.exponentialRampToValueAtTime(520,c.currentTime+4.5);f.type="lowpass";f.frequency.setValueAtTime(5000,c.currentTime);f.frequency.exponentialRampToValueAtTime(500,c.currentTime+4.5);g.gain.setValueAtTime(.075,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+4.5);o.connect(f).connect(g).connect(audio.master);audio.oneShots.add(o);o.onended=function(){audio.oneShots.delete(o)};o.start();o.stop(c.currentTime+4.55)}
function proceduralWind(){var c=ensureAudio();if(!c||S.muted||audio.windSource||!audio.windWanted)return;var len=c.sampleRate*2,b=c.createBuffer(1,len,c.sampleRate),d=b.getChannelData(0);for(var i=0;i<len;i++)d[i]=Math.random()*2-1;var src=c.createBufferSource(),filter=c.createBiquadFilter(),gain=c.createGain();src.buffer=b;src.loop=true;filter.type="lowpass";filter.frequency.value=S.creak?620:420;gain.gain.value=S.creak?.065:.035;src.connect(filter).connect(gain).connect(audio.master);src.start();audio.windSource=src;audio.windGain=gain}
function playDistantCue(){playBuffer("distant",{gain:.52},proceduralDistantCue)}
function playRecedeCue(){playBuffer("recede",{gain:.68},proceduralRecedeCue)}
function startWind(){var generation=++audio.windGeneration;audio.windWanted=true;if(S.muted||audio.windSource)return;playBuffer("wind",{loop:true,ambient:true,gain:S.creak?.48:.32,onstart:function(src,gain){if(!audio.windWanted||generation!==audio.windGeneration){try{src.stop()}catch(e){}return}audio.windSource=src;audio.windGain=gain}},proceduralWind)}
function stopWind(){audio.windWanted=false;audio.windGeneration++;if(audio.windSource){try{audio.windSource.stop()}catch(e){}audio.windSource=null;audio.windGain=null}}
function playCreak(){playBuffer("creak",{gain:.58,rate:.9+Math.random()*.18},function(){tone(150,58,1.15,.07,"sawtooth")})}
function proceduralBadApproach(){var c=ensureAudio();if(!c||S.muted||!(S.phase==="bad-tv"||S.phase==="bad-red"))return;var o=c.createOscillator(),g=c.createGain();o.type="sawtooth";o.frequency.value=43;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.045,c.currentTime+.35);o.connect(g).connect(audio.master);o.start();audio.badSource=o}
function playBadApproach(){playBuffer("bad",{loop:true,ambient:true,gain:.68,valid:function(){return S.phase==="bad-tv"||S.phase==="bad-red"},onstart:function(src){audio.badSource=src}},proceduralBadApproach)}
function stopBadApproach(){if(audio.badSource){try{audio.badSource.stop()}catch(e){}audio.badSource=null}}
E.mute.onclick=function(){setMuted(!S.muted)};
var fitFrame=0;
function fitText(container,text,min,max){if(!container||!text||!container.clientHeight)return;text.style.fontSize=max+"px";var low=min,high=max;for(var i=0;i<8;i++){var size=(low+high)/2;text.style.fontSize=size+"px";if(container.scrollHeight<=container.clientHeight+1&&container.scrollWidth<=container.clientWidth+1)low=size;else high=size}text.style.fontSize=Math.floor(low*10)/10+"px"}
function fitCurrentText(){if(S.phase==="invite")fitText(E.inviteHit,E.inviteCopy,10,24);else if(S.phase==="instructions")fitText(E.instructionPanel,E.instructionTitle,9,15);else if(S.phase==="instructions2")fitText(E.instructionPanel2,E.instructionTitle2,9,16);else if(S.phase==="bad-tv"&&!E.endingBroadcast.hidden)fitText(E.endingBroadcast,E.endingBroadcast,10,24)}
function scheduleTextFit(){cancelAnimationFrame(fitFrame);fitFrame=requestAnimationFrame(fitCurrentText)}
function viewport(){var h=Math.round(window.visualViewport?visualViewport.height:innerHeight);document.documentElement.style.setProperty("--vvh",h+"px");document.documentElement.classList.toggle("vvh-short",h<=640);document.documentElement.classList.toggle("vvh-tiny",h<=520);scheduleTextFit()}
function render(){E.stage.style.transform="translate("+S.tx+"px,"+S.ty+"px) scale("+S.scale+")";E.zoom.textContent=Math.round(S.scale*100)}
function clampPan(){if(S.scale<=1){S.tx=S.ty=0;return}var r=E.vp.getBoundingClientRect(),maxX=r.width*(S.scale-1)/2,maxY=r.height*(S.scale-1)/2;S.tx=Math.max(-maxX,Math.min(maxX,S.tx));S.ty=Math.max(-maxY,Math.min(maxY,S.ty))}
var introMessages=["仕事終わりに、くだらないテレビ番組を見るのが日課だ。","……あれ？　番組が途切れた。","知らない放送が割り込んできた。"];
var photoApproachLogs=["……遠くから歪んだ鯨のような鳴き声が聞こえる","なんだったんだろう。","ひとまず、ここから選べってことか……"];
function hideFlowScreens(){E.intro.hidden=true;E.alert.hidden=true;E.invite.hidden=true;E.instructions.hidden=true;E.instructions2.hidden=true;E.game.hidden=true;E.ending.hidden=true;E.result.hidden=true;E.photoInstructions.hidden=true}
function clearEndingTimers(){S.endingTimers.forEach(clearTimeout);S.endingTimers=[]}
function later(fn,ms){var id=setTimeout(fn,ms);S.endingTimers.push(id);return id}
function showIntro(push){clearTimeout(introTimer);clearEndingTimers();stopOneShots();stopBadApproach();stopWind();hideFlowScreens();E.blackout.hidden=true;E.red.hidden=true;E.ending.className="screen ending-tv-screen";E.intro.hidden=false;S.phase="intro";introStep=0;if(E.introVideo){E.introVideo.hidden=false;E.introVideo.currentTime=0;E.introVideo.muted=S.muted;E.introVideo.volume=.72;E.introVideo.play().catch(function(){})}if(E.introWarning)E.introWarning.hidden=true;if(E.introMessage){E.introMessage.parentElement.hidden=false;E.introMessage.textContent=introMessages[0];E.introMessage.setAttribute("aria-label","メッセージを送る（タップして続ける）")}if(push!==false)pushView()}
function advanceIntro(){if(S.phase!=="intro")return;introStep++;if(introStep===1){if(E.introVideo){E.introVideo.pause();E.introVideo.hidden=true}if(E.introWarning)E.introWarning.hidden=false;cue("interrupt");A.track("intro_interrupted")}else cue("message");if(introStep<introMessages.length){E.introMessage.textContent=introMessages[introStep];return}if(E.introMessage)E.introMessage.parentElement.hidden=true;showAlert()}
function showAlert(push){clearTimeout(introTimer);if(E.introVideo)E.introVideo.pause();hideFlowScreens();E.alert.hidden=false;S.phase="alert";if(push!==false)pushView();E.crt&&E.crt.focus()}
function showInvite(push){hideFlowScreens();E.invite.hidden=false;S.phase="invite";scheduleTextFit();if(push!==false){cue("open");pushView()}E.inviteHit&&E.inviteHit.focus()}
function showInstructions(push){hideFlowScreens();E.instructions.hidden=false;S.phase="instructions";scheduleTextFit();if(push!==false){cue("receive");pushView()}E.instructionPanel.focus()}
function showInstructionTwo(push){hideFlowScreens();E.instructions2.hidden=false;S.phase="instructions2";scheduleTextFit();if(push!==false){cue("receive");pushView()}E.instructionPanel2.focus()}
function triggerFirstTremor(){S.approachLog=0;E.approachLog.textContent=photoApproachLogs[0];E.approachLog.hidden=false;E.game.classList.remove("is-trembling");void E.game.offsetWidth;E.game.classList.add("is-trembling");playDistantCue();A.track("blessing_first_tremor")}
function advanceApproachLog(){if(S.approachLog==null)return false;if(S.approachLog<photoApproachLogs.length-1){S.approachLog++;E.approachLog.textContent=photoApproachLogs[S.approachLog];cue("message");return true}E.approachLog.hidden=true;S.approachLog=null;return false}
function start(reset,push){hideFlowScreens();E.game.hidden=false;if(reset){stopOneShots();S.scale=1.4;S.tx=S.ty=0;S.touches.clear();S.gesture=null;S.ignorePersonClicksUntil=0;S.controls=false;S.revealStarted=0;S.revealed=false;S.selected=null;S.hints=0;S.wind=false;S.creak=false;audio.nextCreak=0;stopWind();E.controls.hidden=true;E.modal.hidden=true;E.sat.value=100;E.bri.value=50;setRevealProgress(0);S.started=performance.now();if(push!==false)cue("photo");A.track("game_start")}else if(!S.started)S.started=performance.now();S.phase="playing";showTvPreview();if(reset&&push!==false)triggerFirstTremor();if(push!==false)pushView();render()}
function showTvPreview(){S.photoMode="preview";E.tvPreview.hidden=false;E.game.classList.add("is-tv-preview");E.game.classList.remove("is-photo-full");E.photoInstructions.hidden=false;E.vp.hidden=true;E.controls.hidden=true}
function enterFullPhoto(push){S.photoMode="full";E.tvPreview.hidden=true;E.game.classList.remove("is-tv-preview");E.game.classList.add("is-photo-full");E.photoInstructions.hidden=false;E.vp.hidden=false;E.controls.hidden=!S.controls;if(push!==false){cue("expand");pushView()}E.vp.focus();A.track("photo_fullscreen")}
function returnToTvPreview(){if(S.phase!=="playing")return;cue("back");historyBack(function(){showTvPreview(false)});A.track("photo_preview_back")}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)} function mid(a,b){return{x:(a.x+b.x)/2,y:(a.y+b.y)/2}}
function capturePointer(id){try{E.vp.setPointerCapture(id)}catch(e){}}
E.vp.addEventListener("pointerdown",function(e){S.touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(S.touches.size===1)S.gesture={kind:"pan",x:e.clientX,y:e.clientY,tx:S.tx,ty:S.ty};if(S.touches.size===2){var p=Array.from(S.touches.values());S.gesture={kind:"pinch",d:dist(p[0],p[1]),scale:S.scale,startScale:S.scale,m:mid(p[0],p[1]),tx:S.tx,ty:S.ty};S.ignorePersonClicksUntil=performance.now()+500;S.touches.forEach(function(_,id){capturePointer(id)})}},true);
E.vp.addEventListener("pointermove",function(e){if(!S.touches.has(e.pointerId))return;S.touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(!S.gesture)return;if(S.touches.size===2&&S.gesture.kind==="pinch"){var p=Array.from(S.touches.values()),currentMid=mid(p[0],p[1]),ratio=dist(p[0],p[1])/S.gesture.d,nextScale=Math.max(1,Math.min(3,S.gesture.scale*ratio)),r=E.vp.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,scaleRatio=nextScale/S.gesture.startScale;S.ignorePersonClicksUntil=performance.now()+500;S.scale=nextScale;S.tx=currentMid.x-cx-scaleRatio*(S.gesture.m.x-cx-S.gesture.tx);S.ty=currentMid.y-cy-scaleRatio*(S.gesture.m.y-cy-S.gesture.ty);if(S.scale===1){S.tx=S.ty=0;unlock()}clampPan();render()}else if(S.touches.size===1&&S.gesture.kind==="pan"&&S.scale>1){var moved=Math.hypot(e.clientX-S.gesture.x,e.clientY-S.gesture.y);if(moved>6){S.ignorePersonClicksUntil=performance.now()+400;capturePointer(e.pointerId)}S.tx=S.gesture.tx+e.clientX-S.gesture.x;S.ty=S.gesture.ty+e.clientY-S.gesture.y;clampPan();render()}});
function pointerUp(e){S.touches.delete(e.pointerId);if(S.touches.size<2){S.gesture=null;render()}} E.vp.addEventListener("pointerup",pointerUp);E.vp.addEventListener("pointercancel",pointerUp);
E.vp.addEventListener("wheel",function(e){e.preventDefault();var down=e.deltaY>0,next=Math.max(1,Math.min(3,S.scale*(down?.9:1.1)));S.scale=next;if(next===1){S.tx=S.ty=0;unlock()}clampPan();render()},{passive:false});
function unlock(){if(S.controls)return;S.controls=true;E.controls.hidden=false;A.track("controls_revealed")}
function smooth(a,b,x){var t=Math.max(0,Math.min(1,(x-a)/(b-a)));return t*t*(3-2*t)}
function setRevealProgress(p){p=Math.max(0,Math.min(1,p));var base=1-smooth(.12,.28,p),subtle=smooth(.12,.28,p)*(1-smooth(.38,.56,p)),partial=smooth(.32,.52,p)*(1-smooth(.65,.82,p)),full=smooth(.65,.88,p),sum=base+subtle+partial+full||1;E.stage.style.setProperty("--base-alpha",base/sum);E.stage.style.setProperty("--subtle-alpha",subtle/sum);E.stage.style.setProperty("--partial-alpha",partial/sum);E.stage.style.setProperty("--full-alpha",full/sum)}
function tune(){var sat=+E.sat.value,bri=+E.bri.value;E.satO.value=sat;E.briO.value=bri;E.stage.style.setProperty("--sat",sat/100);E.stage.style.setProperty("--bri",.55+bri/100);var p=Math.max(0,Math.min(1,((cfg.sat-sat)/Math.max(1,cfg.sat)+(bri-cfg.bri)/Math.max(1,100-cfg.bri)+2)/4));if(sat<=cfg.sat&&bri>=cfg.bri){if(!S.revealStarted)S.revealStarted=performance.now();p=Math.max(p,Math.min(1,(performance.now()-S.revealStarted)/cfg.revealHold));if(performance.now()-S.revealStarted>=cfg.revealHold&&!S.revealed){S.revealed=true;cue("reveal");A.track("entity_revealed");showHint("存在照合：中央個体の生体情報が一致しません。",false)}}else S.revealStarted=0;setRevealProgress(S.revealed?1:p);E.fill.style.setProperty("--progress",Math.round(p*100)+"%")}
E.sat.addEventListener("input",tune);E.bri.addEventListener("input",tune);
$$('.person').forEach(function(b){b.addEventListener("pointerdown",function(e){e.stopPropagation()});b.addEventListener("click",function(e){e.stopPropagation();if(performance.now()<S.ignorePersonClicksUntil){e.preventDefault();return}S.selected=b.dataset.person;cue("select");E.ctitle.textContent=S.selected+"を選定";E.ccopy.textContent="この人物を生贄候補として奉納しますか？ 選定後は取り消せません。";E.modal.hidden=false;E.confirm.focus()})});E.cancel.onclick=function(){cue("cancel");E.modal.hidden=true};E.confirm.onclick=function(){cue("confirm");finish(S.selected==="弟")};
var goodLogs=["気持ちわる、なんだこの写真。","未だよくわからないが、これで正解なのか...?","近づいてきていた歪んだ鳴き声が遠ざかっていく...","急に疲れを感じた俺は、テレビを消した後、気づいたら寝ていた"];
var badLogs=["……あれ？　写真に、知らない男がいる。","泣いているのに、笑っている。","あれは――","おめでとうございます。","あなたの記録は『兄』として保存されました。","次の祝福まで、どうぞ健やかにお過ごしください。"];
function showEndingTv(kind,image,log){clearEndingTimers();hideFlowScreens();E.ending.hidden=false;E.ending.className="screen ending-tv-screen is-"+kind;E.endingImage.src=image;E.endingLog.parentElement.hidden=false;E.endingLog.textContent=log;E.endingBroadcast.hidden=true;E.red.hidden=true;E.blackout.hidden=true;S.phase=kind+"-tv"}
function finish(good){E.modal.hidden=true;stopWind();if(good)startGoodEnding();else startBadEnding()}
function startGoodEnding(){S.goodLog=0;showEndingTv("good","./entity-full-v2.png?v=20260714d",goodLogs[0]);cue("photo");A.track("return_to_tv_for_good_end")}
function advanceGoodEnding(){if(S.phase!=="good-tv")return;if(S.goodLog<goodLogs.length-1){S.goodLog++;E.endingLog.textContent=goodLogs[S.goodLog];cue("message");if(S.goodLog===2){playRecedeCue();A.track("blessing_receding")}return}S.phase="good-tv-off";cue("off");E.ending.classList.add("tv-off");E.endingLog.parentElement.hidden=true;A.track("television_turned_off");later(function(){showResult(true)},cfg.goodOff)}
function startBadEnding(){S.badLog=0;showEndingTv("bad","./family-bad-end-brother-released.png",badLogs[0]);S.wind=true;S.creak=true;startWind();playCreak();A.track("return_to_tv_for_bad_end");playBadApproach()}
function advanceBadEnding(){if(S.phase!=="bad-tv")return;if(S.badLog<2){S.badLog++;E.endingLog.textContent=badLogs[S.badLog];cue("message");return}if(S.badLog<badLogs.length-1){S.badLog++;E.endingLog.parentElement.hidden=true;E.endingBroadcast.hidden=false;E.endingBroadcast.textContent=badLogs[S.badLog];scheduleTextFit();cue("broadcast");return}S.phase="bad-red";cue("red");E.red.hidden=false;A.track("bad_end_red_alert");later(function(){if(S.phase!=="bad-red")return;S.phase="bad-blackout";cue("blackout");stopBadApproach();stopWind();E.blackout.hidden=false;E.red.hidden=true;later(function(){showResult(false)},cfg.badBlack)},cfg.badRed)}
function showResult(good){hideFlowScreens();E.blackout.hidden=true;E.result.hidden=false;E.result.className="screen result-screen "+(good?"good":"bad");$("#result-photo img").src=good?"./entity-full-v2.png?v=20260714d":"./family-bad-end-brother-released.png";$("#result-code").textContent=good?"BLESSING PASSED / SAFE":"BLESSING RECEIVED / REWRITING";$("#result-title").textContent=good?"祝福は通過しました":"おめでとうございます、あなたの元に祝福が訪れました";$("#result-copy").textContent=good?"架空存在を奉納。祝福は去っていきます。":S.selected+"は生身の生贄として捧げられました。";$("#epilogue").textContent=good?"歪んだ鯨のような鳴き声は遠ざかり、夜は静けさを取り戻した。":"その空席を埋めるため、あなたは肉羽家の『兄』として迎えられました。";S.phase=good?"good":"bad";cue(good?"clear":"badresult");A.track(good?"game_clear":"bad_end",{selected:S.selected})}
function showHint(t,sound){if(sound!==false)cue("hint");E.hint.textContent=t;E.hint.classList.add("show");setTimeout(function(){E.hint.classList.remove("show")},6000)}
function loop(now){if(S.phase==="playing"){var e=now-S.started,remaining=Math.max(0,179-Math.floor(e/1000));$("#countdown").textContent="選定期限 "+String(Math.floor(remaining/60)).padStart(2,"0")+":"+String(remaining%60).padStart(2,"0");if(!S.hints&&e>cfg.h1){S.hints=1;showHint("一度きれいに元へ戻す。")}if(S.hints===1&&e>cfg.h2){S.hints=2;showHint("100%まで縮めてみる。")}if(S.revealStarted&&!S.revealed)tune();if(!S.wind&&e>=cfg.wind){S.wind=true;startWind();A.track("blessing_wind_started")}if(!S.creak&&e>=cfg.creak){S.creak=true;stopWind();startWind();audio.nextCreak=now;A.track("blessing_creak_started")}if(S.creak&&now>=audio.nextCreak){playCreak();audio.nextCreak=now+5500+Math.random()*4500}}window.__GAME_STATE__={phase:S.phase,scale:S.scale,controls:S.controls,revealed:S.revealed,selected:S.selected,muted:S.muted,wind:S.wind,creak:S.creak,goodLog:S.goodLog};requestAnimationFrame(loop)}
/* The family photo is the last thing the broadcast shows.  It first appears
   inside the same CRT, then opens into the investigation surface on tap. */
/* The broadcast is deliberately staged: warning first, then the blue
   post-broadcast instruction slate, and only then the photograph. */
function receiveInvite(){if(S.phase!=="invite")return;showInstructions();A.track("blessing_invite_received")}
function openBroadcast(){if(S.phase!=="alert")return;showInvite();A.track("broadcast_open")}
function enterGame(){if(S.phase!=="instructions2")return;start(true);A.track("instruction_panel_next")}
function advancePhotoPreview(){if(S.phase!=="playing"||S.photoMode!=="preview")return;if(advanceApproachLog())return;enterFullPhoto()}
function advanceEnding(){if(S.phase==="good-tv")advanceGoodEnding();else if(S.phase==="bad-tv")advanceBadEnding()}
function isExplicitControl(target){return !!target.closest("button,a,input,select,textarea,label,[role=button],[contenteditable=true]")}
function advanceFromScreenTap(e){
  if(isExplicitControl(e.target))return;
  if(S.phase==="intro")advanceIntro();
  else if(S.phase==="alert")openBroadcast();
  else if(S.phase==="invite")receiveInvite();
  else if(S.phase==="instructions")advanceFromInstruction();
  else if(S.phase==="instructions2")enterGame();
  else if(S.phase==="playing"&&S.photoMode==="preview")advancePhotoPreview();
  else advanceEnding();
}
E.crt.onclick=openBroadcast;
E.crt.onkeydown=function(e){if(e.key==="Enter"||e.key===" "){e.preventDefault();openBroadcast()}};
E.inviteHit.onclick=receiveInvite;
E.inviteHit.onkeydown=function(e){if(e.key==="Enter"||e.key===" "){e.preventDefault();receiveInvite()}};
E.instructionBack.onclick=function(){cue("back");historyBack(function(){showAlert(false)});A.track("broadcast_back")};
E.instructionNext.onclick=function(){advanceFromInstruction();A.track("instruction_next")};
function advanceFromInstruction(){if(S.phase!=="instructions")return;showInstructionTwo();A.track("instruction_second_open")}
E.instructionPanel.onclick=function(e){if(e.target.closest("button"))return;advanceFromInstruction()};
E.instructionPanel.onkeydown=function(e){if(e.key==="Enter"||e.key===" "){e.preventDefault();advanceFromInstruction()}};
E.instructionPanel2.onclick=enterGame;
E.instructionPanel2.onkeydown=function(e){if(e.key==="Enter"||e.key===" "){e.preventDefault();enterGame()}};
E.tvPhotoHit.onclick=advancePhotoPreview;
E.endingHit.onclick=advanceEnding;
E.endingHit.onkeydown=function(e){if(e.key==="Enter"||e.key===" "){e.preventDefault();advanceEnding()}};
E.photoInstructions.onclick=function(){returnToTvPreview();A.track("instructions_viewed")};
E.game.addEventListener("pointerdown",function(e){if(S.phase==="playing"&&S.photoMode==="full"&&!e.target.closest(".photo-viewport")&&!e.target.closest(".develop-controls")&&!e.target.closest(".outside-tv")){returnToTvPreview()}});
E.app.addEventListener("click",advanceFromScreenTap);
document.addEventListener("pointerdown",function(){if(!S.muted){var c=ensureAudio();if(c&&c.state==="suspended")c.resume().catch(function(){})}},{passive:true});
E.restart.onclick=function(){cue("restart");setTimeout(function(){location.reload()},140)};
E.introMessage&&E.introMessage.parentElement.addEventListener("click",advanceIntro);
E.introMessage&&E.introMessage.parentElement.addEventListener("keydown",function(e){if(e.key==="Enter"||e.key===" "){e.preventDefault();advanceIntro()}});
E.introTvHit&&E.introTvHit.addEventListener("click",advanceIntro);
E.introTvHit&&E.introTvHit.addEventListener("keydown",function(e){if(e.key==="Enter"||e.key===" "){e.preventDefault();advanceIntro()}});
function restoreView(key){restoringHistory=true;switch(key){case "intro":showIntro(false);break;case "alert":showAlert(false);break;case "invite":showInvite(false);break;case "instructions":showInstructions(false);break;case "instructions2":showInstructionTwo(false);break;case "photo":start(false,false);enterFullPhoto(false);break;case "tv":start(false,false);break;default:showIntro(false)}restoringHistory=false}
window.addEventListener("popstate",function(e){restoreView(e.state&&e.state.blessingView||"alert")});
if(!history.state||!history.state.blessingView)history.replaceState({blessingView:"intro"},"",location.pathname+location.search+"#intro");
E.instructionFamily.addEventListener("load",scheduleTextFit);window.addEventListener("load",scheduleTextFit);
window.addEventListener("resize",viewport);if(window.visualViewport)visualViewport.addEventListener("resize",viewport);viewport();requestAnimationFrame(loop);
window.gameDebug={unlock:unlock,reveal:function(){unlock();E.sat.value=0;E.bri.value=100;S.revealed=true;tune()},finish:finish,cue:cue,state:function(){return Object.assign({},S)}};
showIntro(false);
})();
